import { GameState } from "./World";

export const ForestGameStart: GameState = {
  worldDescription: "A high fantasy world.",
  history: [
    {
      world: [
        ["", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        [
          "",
          "<Valiant Knight> wants to defend everyone.",
          "",
          "tree",
          "",
          "",
          "",
          "",
          "<Wizard> is here to play tricks on everyone and inject chaos into the scene.",
          "",
          "",
          "",
          "",
          "",
          "",
        ],
        ["", "", "", "tree", "", "", "", "", "", "", "", "", "", "", ""],
        ["", "", "", "tree", "", "", "", "", "", "", "", "", "", "", ""],
        ["", "", "", "tree", "", "", "", "", "", "", "", "", "", "", ""],
        ["", "", "", "tree", "", "", "", "", "", "", "", "", "", "", ""],
        ["", "", "", "tree", "", "", "", "tree", "", "", "", "", "", "", ""],
        ["", "", "", "", "", "", "", "tree", "", "", "", "", "", "", ""],
        ["", "", "", "", "", "", "", "tree", "", "", "", "", "", "", ""],
        [
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "<Lumberjack> wants to cut down trees",
          "",
          "",
          "",
        ],
        [
          "",
          "",
          "<Druid> wants to plant trees and protect them.",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
        ],
        ["", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        ["", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
        [
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "",
          "<Monster> wants to kill everyone!",
          "",
        ],
        ["", "", "", "", "", "", "", "", "", "", "", "", "", "", ""],
      ],
      legend: {},
      cellToLegendMap: {},
      description: "",
    },
  ],
  agents: [
    {
      name: "Valiant Knight",
      color: "red",
      currentState: "<Valiant Knight> wants to defend everyone.",
      privateHistory: [],
      location: {
        row: 1,
        col: 1,
      },
    },
    {
      name: "Monster",
      color: "red",
      currentState: "<Monster> wants to kill everyone!",
      privateHistory: [],
      location: {
        row: 13,
        col: 13,
      },
    },
    {
      name: "Druid",
      color: "red",
      currentState: "<Druid> wants to plant trees and protect them.",
      privateHistory: [],
      location: {
        row: 10,
        col: 2,
      },
    },
    {
      name: "Lumberjack",
      color: "red",
      currentState: "<Lumberjack> wants to cut down trees",
      privateHistory: [],
      location: {
        row: 9,
        col: 11,
      },
    },
    {
      name: "Wizard",
      color: "red",
      currentState:
        "<Wizard> is here to play tricks on everyone and inject chaos into the scene.",
      privateHistory: [],
      location: {
        row: 1,
        col: 8,
      },
    },
  ],
};